Update checkov-cloudrun.yaml

diff --git a/.github/workflows/checkov-cloudrun.yaml b/.github/workflows/checkov-cloudrun.yaml
--- a/.github/workflows/checkov-cloudrun.yaml
+++ b/.github/workflows/checkov-cloudrun.yaml
@@ -27,8 +27,15 @@ jobs:
          repo-token: ${{ secrets.TOKEN }}
          message: |
             ${{ env.CHECKOV_RESULTS }}
-      - name: Block Merge Commits
-        if: ${{ failure() && steps.checkov.outcome == 'failure' }}
-        uses: Morishiri/block-merge-commits-action@v1.0.1
-        with:
-           repo-token: ${{ secrets.TOKEN }}
+      - name: Check for label
+        if: ${{ steps.checkov.outcome == 'failure' , 'do not merge' }}
+        run: |
+          echo "Pull request is labeled as 'do not merge'"
+          echo "This workflow fails so that the pull request cannot be merged"
+          exit 1     
+     #- name: Block Merge Commits
+      #  if: ${{ failure() && steps.checkov.outcome == 'failure' }}
+      #  uses: Morishiri/block-merge-commits-action@v1.0.1
+      #  with:
+      #     repo-token: ${{ secrets.TOKEN }}
+     #  output_format: github_failed_only
